/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.mingoalmacen.vista;

import cl.mingoalmacen.controller.RegistroCarrito;
import cl.mingoalmacen.model.CarritoDeCompras;
import java.awt.Component;
import java.awt.Window;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ayleen
 */
public class JF_Boleta extends javax.swing.JFrame {

    /**
     * Creates new form JF_Boleta
     */
    public JF_Boleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbtn_volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_comprarCarrito = new javax.swing.JTable();
        jbtn_borrarTodo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbtn_verCarrito = new javax.swing.JButton();
        jtxt_total = new javax.swing.JTextField();
        jbtn_calcularTotal = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizando compra");
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jbtn_volver.setBackground(new java.awt.Color(255, 102, 102));
        jbtn_volver.setForeground(new java.awt.Color(255, 102, 102));
        jbtn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/mingoalmacen/img/volver.png"))); // NOI18N
        jbtn_volver.setBorder(null);
        jbtn_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_volverMouseClicked(evt);
            }
        });
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });

        jtbl_comprarCarrito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtbl_comprarCarrito.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jtbl_comprarCarrito.setForeground(new java.awt.Color(102, 102, 102));
        jtbl_comprarCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_comprarCarrito.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbl_comprarCarrito);
        if (jtbl_comprarCarrito.getColumnModel().getColumnCount() > 0) {
            jtbl_comprarCarrito.getColumnModel().getColumn(0).setResizable(false);
            jtbl_comprarCarrito.getColumnModel().getColumn(1).setResizable(false);
            jtbl_comprarCarrito.getColumnModel().getColumn(2).setResizable(false);
        }

        jbtn_borrarTodo.setBackground(new java.awt.Color(255, 102, 102));
        jbtn_borrarTodo.setForeground(new java.awt.Color(255, 102, 102));
        jbtn_borrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/mingoalmacen/img/quitar-carrito (1).png"))); // NOI18N
        jbtn_borrarTodo.setBorder(null);
        jbtn_borrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_borrarTodoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/mingoalmacen/img/pago (1).png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/mingoalmacen/img/efectivo (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtn_verCarrito.setText("Ver mis productos");
        jbtn_verCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_verCarritoActionPerformed(evt);
            }
        });

        jtxt_total.setBackground(new java.awt.Color(255, 102, 102));
        jtxt_total.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jtxt_total.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_total.setText("$");
        jtxt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_totalActionPerformed(evt);
            }
        });

        jbtn_calcularTotal.setBackground(new java.awt.Color(255, 102, 102));
        jbtn_calcularTotal.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jbtn_calcularTotal.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_calcularTotal.setText("Total: ");
        jbtn_calcularTotal.setBorder(null);
        jbtn_calcularTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_calcularTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_verCarrito))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtn_borrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtn_calcularTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtn_verCarrito)
                        .addGap(4, 4, 4)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_calcularTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_borrarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Mostrar un JOptionPane de agradecimiento por la compra
        JOptionPane.showMessageDialog(null, "¡Gracias por su compra y por siempre preferirnos!"+"\n"+"No se pierda nuestras ofertas de la próxima semana."+"\n"+"\t\t¡Lo esperamos!", "Compra Exitosa", JOptionPane.INFORMATION_MESSAGE);

        // Llamar al método para borrar los elementos del carrito
        RegistroCarrito rc = new RegistroCarrito();
        boolean elementosBorrados = rc.borrarTodo();

        if (elementosBorrados) {
            JOptionPane.showMessageDialog(null, "Ha comprado todo los producto del carrito. Por favor, vuelva atrás si desea seguir comprando.");
        } else {
            JOptionPane.showMessageDialog(null, "No se han encontrado elementos en el carrito para borrar.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtn_borrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_borrarTodoActionPerformed
        RegistroCarrito rc = new RegistroCarrito();
        boolean borrado = rc.borrarTodo();

        if (borrado) {
            JOptionPane.showMessageDialog(null, "Se han borrado todos los elementos del carrito.");
        } else {
            JOptionPane.showMessageDialog(null, "No se han encontrado elementos en el carrito para borrar.");
        }
    }//GEN-LAST:event_jbtn_borrarTodoActionPerformed

    private void jbtn_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_volverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_volverMouseClicked

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        Window ventana = SwingUtilities.getWindowAncestor((Component) evt.getSource());

        // Cerrar la ventana actual
        if (ventana instanceof JF_Boleta) {
            ((JF_Boleta) ventana).dispose();
        }
    }//GEN-LAST:event_jbtn_volverActionPerformed

    private void jbtn_verCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_verCarritoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_comprarCarrito.getModel();
        modelo.setRowCount(0); // Limpiamos el modelo de la tabla

        RegistroCarrito rc = new RegistroCarrito();
        List<CarritoDeCompras> lista = rc.buscarTodos();

        for (CarritoDeCompras carrito : lista) {
            String nombreProd = carrito.getNombre_prod();
            int cantidad = carrito.getCantidad();
            int precio = carrito.getPrecio();

            modelo.addRow(new Object[]{nombreProd, cantidad, precio});
        }
    }//GEN-LAST:event_jbtn_verCarritoActionPerformed

    private void jtxt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_totalActionPerformed
//        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_comprarCarrito.getModel();
//        modelo.setRowCount(0); // Limpiamos el modelo de la tabla
//
//        RegistroCarrito rc = new RegistroCarrito();
//        List<CarritoDeCompras> lista = rc.buscarTodos();
//
//        Double totalVenta = rc.calcularTotalCompra(lista); // Calcular el total de la venta
//
//        // Mostrar los datos en la tabla
//        for (CarritoDeCompras carrito : lista) {
//            String nombreProd = carrito.getNombre_prod();
//            int precio = carrito.getPrecio();
//            int cantidad = carrito.getCantidad();
//
//            modelo.addRow(new Object[]{nombreProd, precio, cantidad});
//        }
//
//        // Mostrar el total en el campo jtxt_total
//        jtxt_total.setText(String.valueOf(totalVenta));
    }//GEN-LAST:event_jtxt_totalActionPerformed

    private void jbtn_calcularTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_calcularTotalActionPerformed
        RegistroCarrito rc = new RegistroCarrito();
        List<CarritoDeCompras> lista = rc.buscarTodos();

        double totalVenta = rc.calcularTotalCompra(lista);

        // Aquí puedes mostrar el total en un campo de texto, etiqueta o cualquier componente que desees
        jtxt_total.setText(String.valueOf("$" + totalVenta));
    }//GEN-LAST:event_jbtn_calcularTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Boleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_borrarTodo;
    private javax.swing.JButton jbtn_calcularTotal;
    private javax.swing.JButton jbtn_verCarrito;
    private javax.swing.JButton jbtn_volver;
    private javax.swing.JTable jtbl_comprarCarrito;
    private javax.swing.JTextField jtxt_total;
    // End of variables declaration//GEN-END:variables
}
