/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.mingoalmacen.vista;

import cl.mingoalmacen.controller.ControladorProducto;
import cl.mingoalmacen.controller.RegistroCarrito;
import cl.mingoalmacen.img.ImagenLogin;
import cl.mingoalmacen.model.CarritoDeCompras;
import cl.mingoalmacen.model.Producto;
import cl.mingoalmacen.utilities.Validador;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ayleen
 */
public class JF_CarritoCompras extends javax.swing.JFrame {

    /**
     * Creates new form JF_CarritoCompras
     */
    public JF_CarritoCompras() {
        initComponents();
        ImagenLogin.cambiarIconoJFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_productos = new javax.swing.JTable();
        jbtn_listarProd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtxt_nombreBusc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxt_precioBusc = new javax.swing.JTextField();
        jbtn_nombreBusc1 = new javax.swing.JButton();
        jbtn_precioBusc1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxt_nomProdAgregar = new javax.swing.JTextField();
        jtxt_precioProdAgregar = new javax.swing.JTextField();
        jtxt_cantidadProdAgregar = new javax.swing.JTextField();
        jbtn_agregarProdCarrito = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_carritoConProductos = new javax.swing.JTable();
        jbtn_actualizarCarrito = new javax.swing.JButton();
        jbtn_eliminarPorNombre = new javax.swing.JButton();
        jtxt_nomProdEliminar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmi_cerrarVentana = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("El Mingo Almacén - Inventario");
        setMaximumSize(new java.awt.Dimension(1009, 697));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jtbl_productos.setBackground(new java.awt.Color(255, 204, 204));
        jtbl_productos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        jtbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio", "Stock Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_productos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbl_productos);
        if (jtbl_productos.getColumnModel().getColumnCount() > 0) {
            jtbl_productos.getColumnModel().getColumn(0).setResizable(false);
            jtbl_productos.getColumnModel().getColumn(1).setResizable(false);
            jtbl_productos.getColumnModel().getColumn(2).setResizable(false);
            jtbl_productos.getColumnModel().getColumn(3).setResizable(false);
        }

        jbtn_listarProd.setText("Listar Productos");
        jbtn_listarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_listarProd.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/mingoalmacen/img/verduras.png"))); // NOI18N
        jbtn_listarProd.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/mingoalmacen/img/verduras (1).png"))); // NOI18N
        jbtn_listarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listarProdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Productos disponibles:");

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "¿Qué desea hacer?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jtxt_nombreBusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombreBuscActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar productos por:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio menor a: ");

        jtxt_precioBusc.setBackground(new java.awt.Color(242, 242, 242));
        jtxt_precioBusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_precioBuscActionPerformed(evt);
            }
        });

        jbtn_nombreBusc1.setText("Buscar");
        jbtn_nombreBusc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_nombreBusc1MouseClicked(evt);
            }
        });
        jbtn_nombreBusc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_nombreBusc1ActionPerformed(evt);
            }
        });

        jbtn_precioBusc1.setText("Buscar");
        jbtn_precioBusc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_precioBusc1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Agregar productos al Carrito de Compras");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio:");

        jtxt_nomProdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nomProdAgregarActionPerformed(evt);
            }
        });

        jtxt_precioProdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_precioProdAgregarActionPerformed(evt);
            }
        });

        jbtn_agregarProdCarrito.setBackground(new java.awt.Color(255, 153, 153));
        jbtn_agregarProdCarrito.setForeground(new java.awt.Color(255, 153, 153));
        jbtn_agregarProdCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/mingoalmacen/img/compra (1).png"))); // NOI18N
        jbtn_agregarProdCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_agregarProdCarrito.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jbtn_agregarProdCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_agregarProdCarritoMouseClicked(evt);
            }
        });
        jbtn_agregarProdCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarProdCarritoActionPerformed(evt);
            }
        });

        jtbl_carritoConProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_carritoConProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtbl_carritoConProductos);
        if (jtbl_carritoConProductos.getColumnModel().getColumnCount() > 0) {
            jtbl_carritoConProductos.getColumnModel().getColumn(0).setResizable(false);
            jtbl_carritoConProductos.getColumnModel().getColumn(1).setResizable(false);
            jtbl_carritoConProductos.getColumnModel().getColumn(2).setResizable(false);
        }

        jbtn_actualizarCarrito.setText("Actualizar resultados");
        jbtn_actualizarCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_actualizarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_actualizarCarritoActionPerformed(evt);
            }
        });

        jbtn_eliminarPorNombre.setText("Eliminar por nombre");
        jbtn_eliminarPorNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_eliminarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarPorNombreActionPerformed(evt);
            }
        });

        jtxt_nomProdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nomProdEliminarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/mingoalmacen/img/carro.png"))); // NOI18N
        jButton1.setText("Finalizar compra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Su Carrito de Compras:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGap(50, 50, 50)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtxt_precioBusc))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGap(98, 98, 98)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jtxt_nombreBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(jbtn_nombreBusc1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(jbtn_precioBusc1)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxt_precioProdAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_nomProdAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_cantidadProdAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_agregarProdCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jbtn_actualizarCarrito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jbtn_eliminarPorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxt_nomProdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_nombreBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_nombreBusc1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_precioBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_precioBusc1))
                .addGap(28, 28, 28)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxt_nomProdAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_precioProdAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_cantidadProdAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jbtn_agregarProdCarrito))
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_actualizarCarrito)
                    .addComponent(jbtn_eliminarPorNombre)
                    .addComponent(jtxt_nomProdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_listarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_listarProd))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 204));

        jMenu2.setText("Salir");

        jmi_cerrarVentana.setText("Cerrar Ventana");
        jmi_cerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cerrarVentanaActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_cerrarVentana);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_listarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listarProdActionPerformed
        int idProd;
        String nombreProd;
        int precio;
        int stock;

        ControladorProducto cp = new ControladorProducto();
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_productos.getModel();

        modelo.setRowCount(0);

        List<Producto> lista = cp.buscarTodos();

        for (Producto producto : lista) {
            idProd = producto.getId_prod();
            nombreProd = producto.getNombre_prod();
            precio = producto.getPrecio();
            stock = producto.getStock();

            modelo.addRow(new Object[]{idProd, nombreProd, precio, stock});
        }
    }//GEN-LAST:event_jbtn_listarProdActionPerformed

    private void jtxt_nombreBuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombreBuscActionPerformed

    }//GEN-LAST:event_jtxt_nombreBuscActionPerformed

    private void jtxt_precioBuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_precioBuscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_precioBuscActionPerformed

    private void jbtn_nombreBusc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_nombreBusc1ActionPerformed

        String nombreProd = this.jtxt_nombreBusc.getText(); // Obtener el nombre del campo de texto

        if (nombreProd.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo de búsqueda no puede estar vacío.");
            return; // Salir del método si el campo está vacío
        }

        int idProd;
        int precio;
        int stock;

        ControladorProducto cp = new ControladorProducto();
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_productos.getModel();

        modelo.setRowCount(0);

        List<Producto> prodBusc = cp.buscarPorNombre(nombreProd);

        for (Producto producto : prodBusc) {
            idProd = producto.getId_prod();
            nombreProd = producto.getNombre_prod();
            precio = producto.getPrecio();
            stock = producto.getStock();

            modelo.addRow(new Object[]{idProd, nombreProd, precio, stock});
        }

        this.jtxt_nombreBusc.setText("");


    }//GEN-LAST:event_jbtn_nombreBusc1ActionPerformed

    private void jbtn_precioBusc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_precioBusc1ActionPerformed
        double precioIngresado;
        try {
            precioIngresado = Double.parseDouble(this.jtxt_precioBusc.getText()); // Obtener el precio ingresado
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un número válido para el precio.");
            return;
        }

        int idProd;
        String nombreProd;
        double precio;
        int stock;

        ControladorProducto cp = new ControladorProducto();
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_productos.getModel();

        modelo.setRowCount(0);

        List<Producto> prodBusc = cp.buscarPorPrecioInferior(precioIngresado);

        for (Producto producto : prodBusc) {
            idProd = producto.getId_prod();
            nombreProd = producto.getNombre_prod();
            precio = producto.getPrecio();
            stock = producto.getStock();

            modelo.addRow(new Object[]{idProd, nombreProd, precio, stock});
        }
        this.jtxt_precioBusc.setText("");
    }//GEN-LAST:event_jbtn_precioBusc1ActionPerformed

    private void jbtn_nombreBusc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_nombreBusc1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_nombreBusc1MouseClicked

    private void jtxt_nomProdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nomProdAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nomProdAgregarActionPerformed

    private void jtxt_precioProdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_precioProdAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_precioProdAgregarActionPerformed

    private void jbtn_agregarProdCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_agregarProdCarritoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_agregarProdCarritoMouseClicked

    private void jbtn_agregarProdCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarProdCarritoActionPerformed
        // Obtener los valores de los campos de texto
        String nombre = jtxt_nomProdAgregar.getText();
        String precioText = jtxt_precioProdAgregar.getText();
        String cantidadText = jtxt_cantidadProdAgregar.getText();

        Validador valida = new Validador();

        // Validar que el nombre contenga solo texto
        if (!valida.esTextoValido(nombre)) {
            JOptionPane.showMessageDialog(null, "Ingrese un nombre válido (solo texto).");
            return;
        }

        // Validar que el precio y la cantidad contengan solo números
        if (!valida.esNumeroValido(precioText) || !valida.esNumeroValido(cantidadText)) {
            JOptionPane.showMessageDialog(null, "Ingrese valores numéricos para precio y cantidad.");
            return;
        }

        // Verificar si los campos están vacíos
        if (nombre.isEmpty() || precioText.isEmpty() || cantidadText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacíos.");
            return; // Salir del método si hay campos vacíos
        }

        // Convertir a tipo int si los campos no están vacíos
        int precio = Integer.parseInt(precioText);
        int cantidad = Integer.parseInt(cantidadText);

        // Crear un objeto Producto con los datos ingresados
        CarritoDeCompras carrito = new CarritoDeCompras(precio, nombre, cantidad);

        // Llamar al método para agregar el producto al carrito
        boolean agregado = RegistroCarrito.agregarProdCarrito(carrito);

        if (agregado) {
            JOptionPane.showMessageDialog(null, "Producto agregado al carrito exitosamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo agregar el producto al carrito. Verifique que el producto exista.");
        }

        // Limpiar los campos de texto
        this.jtxt_nomProdAgregar.setText("");
        this.jtxt_precioProdAgregar.setText("");
        this.jtxt_cantidadProdAgregar.setText("");

    }//GEN-LAST:event_jbtn_agregarProdCarritoActionPerformed

    private void jbtn_actualizarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_actualizarCarritoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_carritoConProductos.getModel();
        modelo.setRowCount(0); // Limpiamos el modelo de la tabla

        RegistroCarrito rc = new RegistroCarrito();
        List<CarritoDeCompras> lista = rc.buscarTodos();

        for (CarritoDeCompras carrito : lista) {
            String nombreProd = carrito.getNombre_prod();
            int precio = carrito.getPrecio();
            int cantidad = carrito.getCantidad();

            modelo.addRow(new Object[]{nombreProd, precio, cantidad});
        }

        // Habilita o deshabilita el botón jButton1 según el estado de la tabla
        jButton1.setEnabled(jtbl_carritoConProductos.getRowCount() > 0);
    }//GEN-LAST:event_jbtn_actualizarCarritoActionPerformed

    /**
     * Uso del Metodo RegistroCarrito.eliminarProdCarrito()
     */
    private void jbtn_eliminarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarPorNombreActionPerformed

        String nombreProductoABorrar = jtxt_nomProdEliminar.getText(); // Obtener el nombre del producto a eliminar

        if (nombreProductoABorrar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacíos.");
            return; // Salir del método si hay campos vacíos
        }

        RegistroCarrito rc = new RegistroCarrito();

        boolean eliminado = rc.eliminarProdCarrito(nombreProductoABorrar);

        if (eliminado) {
            JOptionPane.showMessageDialog(null, "Producto eliminado del carrito exitosamente." + "\n" + "Por favor, actualice los resultados.");

        } else {
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el producto del carrito." + "\n" + "Por favor, verifique si está correctamente escrito.");

        }

        // Actualizar la tabla después de eliminar el producto
        jbtn_actualizarCarritoActionPerformed(evt);


    }//GEN-LAST:event_jbtn_eliminarPorNombreActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jmi_cerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cerrarVentanaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jmi_cerrarVentanaActionPerformed

    private void jtxt_nomProdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nomProdEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nomProdEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jtbl_carritoConProductos.getRowCount() > 0) {
            JF_Boleta boleta = new JF_Boleta();
            boleta.setVisible(true);
        } else {
            // Muestra un mensaje o realiza alguna acción si la tabla está vacía
            // Por ejemplo:
            JOptionPane.showMessageDialog(this, "El carrito está vacío, no se puede generar la boleta.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_CarritoCompras.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_CarritoCompras.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_CarritoCompras.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_CarritoCompras.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_CarritoCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtn_actualizarCarrito;
    private javax.swing.JButton jbtn_agregarProdCarrito;
    private javax.swing.JButton jbtn_eliminarPorNombre;
    private javax.swing.JButton jbtn_listarProd;
    private javax.swing.JButton jbtn_nombreBusc1;
    private javax.swing.JButton jbtn_precioBusc1;
    private javax.swing.JMenuItem jmi_cerrarVentana;
    private javax.swing.JTable jtbl_carritoConProductos;
    private javax.swing.JTable jtbl_productos;
    private javax.swing.JTextField jtxt_cantidadProdAgregar;
    private javax.swing.JTextField jtxt_nomProdAgregar;
    private javax.swing.JTextField jtxt_nomProdEliminar;
    private javax.swing.JTextField jtxt_nombreBusc;
    private javax.swing.JTextField jtxt_precioBusc;
    private javax.swing.JTextField jtxt_precioProdAgregar;
    // End of variables declaration//GEN-END:variables
}
