/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.mingoalmacen.vista;

import DAO.ClienteDAO;
import cl.mingoalmacen.controller.ControladorLogin;
import cl.mingoalmacen.controller.RegistroCarrito;
import cl.mingoalmacen.img.ImagenLogin;
import cl.mingoalmacen.model.Cliente;
import static cl.mingoalmacen.utilities.Validador.validarCorreo;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ayleen
 */
public class JF_Login extends javax.swing.JFrame {

    /**
     * Creates new form JF_Login
     */
    public JF_Login() {
        initComponents();
        ImagenLogin.cambiarIconoJFrame(this);
        RegistroCarrito rc = new RegistroCarrito();
        rc.borrarTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jp_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxt_correoElectronico = new javax.swing.JTextField();
        jbtn_entrar = new javax.swing.JButton();
        jpass_contrasena = new javax.swing.JPasswordField();
        jbtn_registrar = new javax.swing.JButton();
        jp_img = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_salir = new javax.swing.JMenu();
        jmi_cerrarSesion = new javax.swing.JMenuItem();

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("El Mingo Almacén - Inicio");
        setBackground(new java.awt.Color(255, 102, 102));
        setMaximumSize(new java.awt.Dimension(800, 705));
        setPreferredSize(new java.awt.Dimension(800, 705));

        jp_login.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("¡Bienvenido a Verduleria Online");
        jLabel1.setToolTipText("");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("El Mingo!");
        jLabel5.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Correo electrónico:");
        jLabel3.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Contraseña:");
        jLabel4.setToolTipText("");

        jtxt_correoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_correoElectronicoActionPerformed(evt);
            }
        });

        jbtn_entrar.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jbtn_entrar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jbtn_entrar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_entrar.setText("Entrar");
        jbtn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_entrarActionPerformed(evt);
            }
        });

        jpass_contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpass_contrasenaActionPerformed(evt);
            }
        });

        jbtn_registrar.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jbtn_registrar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jbtn_registrar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_registrar.setText("Registrar");
        jbtn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_loginLayout = new javax.swing.GroupLayout(jp_login);
        jp_login.setLayout(jp_loginLayout);
        jp_loginLayout.setHorizontalGroup(
            jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_loginLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_loginLayout.createSequentialGroup()
                        .addGroup(jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_correoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpass_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_loginLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(311, 311, 311))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_loginLayout.createSequentialGroup()
                        .addComponent(jbtn_registrar)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(313, 313, 313))))
        );
        jp_loginLayout.setVerticalGroup(
            jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_loginLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_correoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jpass_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_entrar)
                    .addComponent(jbtn_registrar))
                .addGap(27, 27, 27))
        );

        jp_img.setBackground(new java.awt.Color(229, 229, 229));

        jLabel2.setBackground(new java.awt.Color(100, 0, 0));
        jLabel2.setForeground(new java.awt.Color(97, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/mingoalmacen/img/Screenshot_7.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_imgLayout = new javax.swing.GroupLayout(jp_img);
        jp_img.setLayout(jp_imgLayout);
        jp_imgLayout.setHorizontalGroup(
            jp_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_imgLayout.setVerticalGroup(
            jp_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu_salir.setText("Salir");

        jmi_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/mingoalmacen/img/salida.png"))); // NOI18N
        jmi_cerrarSesion.setText("Cerrar sesión");
        jmi_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cerrarSesionActionPerformed(evt);
            }
        });
        jMenu_salir.add(jmi_cerrarSesion);

        jMenuBar1.add(jMenu_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jp_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cerrarSesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmi_cerrarSesionActionPerformed

    private void jtxt_correoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_correoElectronicoActionPerformed


    }//GEN-LAST:event_jtxt_correoElectronicoActionPerformed

    private void actualizarEstadoBotonEntrar() {
        String usuario = jtxt_correoElectronico.getText();
        String contrasena = new String(jpass_contrasena.getPassword());

        Cliente cliente = new Cliente();
        boolean usuarioValido = cliente.validarNombreUsuario(usuario);
        boolean contrasenaValida = cliente.validarContrasena(contrasena);

        jbtn_entrar.setEnabled(usuarioValido && contrasenaValida);
    }

    private void jbtn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_entrarActionPerformed
        String nombreUsuario = jtxt_correoElectronico.getText();
        String contrasena = new String(jpass_contrasena.getPassword());

        if (nombreUsuario.isEmpty() || contrasena.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacíos.");
            return; // Salir del método si hay campos vacíos
        }

        ControladorLogin controladorLogin = new ControladorLogin();
        boolean credencialesValidas = controladorLogin.verificarCredenciales(nombreUsuario, contrasena);

        if (credencialesValidas) {
            JOptionPane.showMessageDialog(null, "Ingreso exitoso", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);

            // Abre la ventana del carrito de compras
            JF_CarritoCompras carrito = new JF_CarritoCompras();
            carrito.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos", "Error de ingreso", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbtn_entrarActionPerformed


    private void jpass_contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpass_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpass_contrasenaActionPerformed

    private void jbtn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_registrarActionPerformed
        jpass_contrasena.setEchoChar('*');

        String nombreUsuario = jtxt_correoElectronico.getText();
        String contrasena = new String(jpass_contrasena.getPassword());

        Cliente cliente = new Cliente();
        ClienteDAO clienteDAO = new ClienteDAO();

        boolean nombreValido = cliente.validarNombreUsuario(nombreUsuario);
        boolean contrasenaValida = cliente.validarContrasena(contrasena);
        boolean nombreUsuarioExistente = clienteDAO.existeNombreUsuario(nombreUsuario);
        boolean correoValido = validarCorreo(nombreUsuario);

        //mostrar mensaje de error según el error
        if (nombreUsuario.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: El usuario y la contraseña no pueden estar vacíos.", "Error de registro", JOptionPane.ERROR_MESSAGE);
        } else if (!nombreValido) {
            JOptionPane.showMessageDialog(null, "Error: Debe ser formato correo electrónico.", "Error de registro", JOptionPane.ERROR_MESSAGE);
        } else if (!contrasenaValida) {
            JOptionPane.showMessageDialog(null, "Error: La contraseña no puede estar vacía.", "Error de registro", JOptionPane.ERROR_MESSAGE);
        } else if (!correoValido) {
            JOptionPane.showMessageDialog(null, "Error: El correo electrónico no es válido.", "Error de registro", JOptionPane.ERROR_MESSAGE);
        } else if (nombreUsuarioExistente) {
            JOptionPane.showMessageDialog(null, "El nombre de usuario ya está en uso. Por favor, elija otro.", "Error de registro", JOptionPane.ERROR_MESSAGE);
        } else {
            // Si todo es válido y el nombre de usuario no existe, proceder con el registro
            ControladorLogin controladorLogin = new ControladorLogin();
            controladorLogin.registrarUsuario(nombreUsuario, contrasena);
            JOptionPane.showMessageDialog(null, "Usuario registrado con éxito" + "\n" + "Ahora pulse el botón Entrar.", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenu_salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_entrar;
    private javax.swing.JButton jbtn_registrar;
    private javax.swing.JMenuItem jmi_cerrarSesion;
    private javax.swing.JPanel jp_img;
    private javax.swing.JPanel jp_login;
    private javax.swing.JPasswordField jpass_contrasena;
    private javax.swing.JTextField jtxt_correoElectronico;
    // End of variables declaration//GEN-END:variables
}
